--조건에 부합하는 중고거래 댓글 조회하기
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE from USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGB.CREATED_DATE >= '2022-10-01' AND UGB.CREATED_DATE <= '2022-10-31'
ORDER BY UGR.CREATED_DATE, UGB.TITLE ASC

--모든 레코드 조회하기
SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID;

-- 여러 기준으로 정렬하기
SELECT AI.ANIMAL_ID, AI.NAME, AI.DATETIME FROM (SELECT AI.ANIMAL_ID, AI.NAME, AI.DATETIME, RANK() OVER (partition by AI.NAME ORDER BY AI.DATETIME DESC) FROM ANIMAL_INS AI
ORDER BY AI.NAME ASC) AI;

-- 이름이 있는 동물의 아이디
SELECT AI.ANIMAL_ID FROM ANIMAL_INS AI
WHERE AI.NAME is NOT NULL
ORDER BY AI.ANIMAL_ID ASC;

-- 상위 n개 레코드
SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1;
